# Generated by Django 4.2.11 on 2024-04-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqola',
            name='tag',
            field=models.CharField(choices=[('world', 'world'), ('local', 'local'), ('sport', 'sport')], default=-1, max_length=255),
            preserve_default=False,
        ),
    ]
