# Generated by Django 4.2.11 on 2024-05-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_maqola_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqola',
            name='imge',
            field=models.ImageField(default=-1, upload_to=''),
            preserve_default=False,
        ),
    ]
