# Generated by Django 4.2.11 on 2024-05-01 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_maqola_imge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maqola',
            old_name='imge',
            new_name='image',
        ),
    ]
